# Generated by Django 6.0.1 on 2026-02-02 22:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sector', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pos_menus',
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.menu')),
            ],
            options={
                'db_table': 'pos_menu_items',
                'ordering': ['menu', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('payment_intent', models.CharField(choices=[('pay_now', 'Pay Now'), ('post_to_room', 'Post to Room')], default='pay_now', max_length=20)),
                ('table_or_room', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders_created', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='hotel.folio')),
            ],
            options={
                'db_table': 'pos_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pos.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
            ],
            options={
                'db_table': 'pos_order_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sector'], name='pos_orders_sector_d5c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='pos_orders_status_c62d41_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='pos_orders_created_c4331b_idx'),
        ),
    ]
