# Generated by Django 6.0.1 on 2026-02-02 22:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('id_type', models.CharField(blank=True, max_length=32)),
                ('id_number', models.CharField(blank=True, max_length=64)),
                ('nationality', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=8)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('source', models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-in')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('qr_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.roomtype')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='hotel.booking')),
            ],
            options={
                'db_table': 'folios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('rooms', 'Rooms'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping'), ('activities', 'Activities')], max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('pos_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('room_night_date', models.DateField(blank=True, null=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='hotel.folio')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folio_charges',
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], max_length=32)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.folio')),
            ],
            options={
                'db_table': 'folio_payments',
                'ordering': ['confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('folio_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='hotel.foliopayment')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expense_recorded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hotel.room')),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_requests', to='hotel.room')),
            ],
            options={
                'db_table': 'housekeeping_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel.roomtype'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['booking'], name='folios_booking_bcd5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['status'], name='folios_status_7fd11a_idx'),
        ),
        migrations.AddIndex(
            model_name='foliocharge',
            index=models.Index(fields=['folio'], name='folio_charg_folio_i_0820f5_idx'),
        ),
        migrations.AddIndex(
            model_name='foliocharge',
            index=models.Index(fields=['sector'], name='folio_charg_sector_879519_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_check_i_73f05f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['qr_token'], name='bookings_qr_toke_55cb43_idx'),
        ),
    ]
