# Generated by Django 6.0.1 on 2026-02-02 22:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=16)),
                ('sectors', models.JSONField(default=list, help_text='List of sector codes, e.g. ["rooms","restaurant"]. Empty = all.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'taxes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('job_title', models.CharField(blank=True, max_length=128)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.department')),
            ],
            options={
                'db_table': 'staff_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('rooms', 'Rooms'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping'), ('activities', 'Activities'), ('general', 'General')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sector'], name='expenses_sector_ce88a7_idx'), models.Index(fields=['created_at'], name='expenses_created_753bda_idx')],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('month', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='finance.staffprofile')),
            ],
            options={
                'db_table': 'salaries',
                'ordering': ['-month'],
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
