/**
 * Shared HMS PDF branding utilities for all report PDFs.
 * Global design: consistent margins (30), typography, table styles.
 */

export const PDF_MARGIN = 30;
export const TABLE_HEADER_BG = '#e5e7eb';
export const TABLE_ROW_STRIPE = '#f8fafc';
export const TABLE_BORDER = '#9ca3af';
export const TABLE_BORDER_LIGHT = '#d1d5db';

export function formatMoney(n: number): string {
  const v = Number(n ?? 0);
  const safe = Number.isFinite(v) ? v : 0;
  return new Intl.NumberFormat('en-TZ', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(safe);
}

export function toTitleCase(s: string): string {
  return String(s || '')
    .toLowerCase()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function formatDateTime(d: Date): string {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, '0');
  const min = String(d.getMinutes()).padStart(2, '0');
  return `${dd}/${mm}/${yyyy} ${hh}:${min}`;
}

const LOGO_MAX_HEIGHT = 60;
const LOGO_MAX_WIDTH = 140;
const HEADER_LEFT_W = 150;

export function drawHmsReportHeader(
  doc: any,
  input: {
    title: string;
    businessName: string;
    branchId: string;
    dateRange: { from?: Date | string; to?: Date | string };
    generatedAt: Date;
    generatedBy: string;
    logoBuffer?: Buffer | null;
  },
): number {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const x = doc.page.margins.left;
  const top = doc.page.margins.top;
  const leftW = HEADER_LEFT_W;
  const rightW = 180;
  const centerW = pageWidth - leftW - rightW - 24;
  const leftX = x;
  const centerX = x + leftW + 12;
  const rightX = centerX + centerW + 12;

  const hasLogo = input.logoBuffer && Buffer.isBuffer(input.logoBuffer) && input.logoBuffer.length > 0;

  if (hasLogo) {
    try {
      doc.image(input.logoBuffer!, leftX, top, {
        fit: [LOGO_MAX_WIDTH, LOGO_MAX_HEIGHT],
        align: 'left',
        valign: 'top',
      });
    } catch {
      doc.font('Helvetica-Bold').fontSize(24).fillColor('#000');
      doc.text('HMS', leftX, top, { width: leftW, lineBreak: false, characterSpacing: 2 });
    }
  } else {
    doc.font('Helvetica-Bold').fontSize(24).fillColor('#000');
    doc.text('HMS', leftX, top, { width: leftW, lineBreak: false, characterSpacing: 2 });
  }

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#000');
  doc.text(input.title, centerX, top + (hasLogo ? 12 : 4), { width: centerW, align: 'center', lineBreak: false });

  doc.font('Helvetica').fontSize(9).fillColor('#374151');
  const f = input.dateRange?.from ? (typeof input.dateRange.from === 'string' ? input.dateRange.from : input.dateRange.from.toISOString().slice(0, 10)) : '-';
  const t = input.dateRange?.to ? (typeof input.dateRange.to === 'string' ? input.dateRange.to : input.dateRange.to.toISOString().slice(0, 10)) : '-';
  doc.text(input.businessName, rightX, top, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Branch: ${input.branchId || '-'}`, rightX, top + 12, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Period: ${f} to ${t}`, rightX, top + 24, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Generated: ${formatDateTime(input.generatedAt)}`, rightX, top + 36, { width: rightW, align: 'right', lineBreak: false });

  const headerBottom = top + Math.max(LOGO_MAX_HEIGHT, 44);
  doc.moveTo(x, headerBottom).lineTo(x + pageWidth, headerBottom).lineWidth(0.5).strokeColor('#9ca3af').stroke();
  doc.strokeColor('#000');
  return headerBottom + 12;
}

export function applyHmsPageFooter(doc: any): void {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const x = doc.page.margins.left;
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const footerY = doc.page.height - doc.page.margins.bottom - 14;
    doc.font('Helvetica').fontSize(9).fillColor('#6b7280');
    doc.text('Generated by HMS', x, footerY, { width: pageWidth / 2, align: 'left' });
    doc.text(`Page ${i + 1} of ${range.count}`, x, footerY, { width: pageWidth, align: 'right' });
    doc.fillColor('#000');
  }
}
