/**
 * Shared HMS PDF branding utilities for all report PDFs.
 */

function formatDateTime(d: Date): string {
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, '0');
  const min = String(d.getMinutes()).padStart(2, '0');
  return `${dd}/${mm}/${yyyy} ${hh}:${min}`;
}

export function drawHmsReportHeader(
  doc: any,
  input: {
    title: string;
    subtitle?: string;
    businessName: string;
    branchId: string;
    dateRange: { from?: Date | string; to?: Date | string };
    generatedAt: Date;
    generatedBy: string;
  },
): number {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const x = doc.page.margins.left;
  const top = doc.page.margins.top;
  const leftW = 100;
  const rightW = 180;
  const centerW = pageWidth - leftW - rightW - 24;
  const leftX = x;
  const centerX = x + leftW + 12;
  const rightX = centerX + centerW + 12;

  doc.font('Helvetica-Bold').fontSize(14).fillColor('#000');
  doc.text('HMS', leftX, top, { width: leftW, lineBreak: false });
  if (input.subtitle) {
    doc.font('Helvetica').fontSize(8).fillColor('#6b7280');
    doc.text(input.subtitle, leftX, top + 16, { width: leftW, lineBreak: false });
  }

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#000');
  doc.text(input.title, centerX, top + 4, { width: centerW, align: 'center', lineBreak: false });

  doc.font('Helvetica').fontSize(9).fillColor('#374151');
  const f = input.dateRange?.from ? (typeof input.dateRange.from === 'string' ? input.dateRange.from : input.dateRange.from.toISOString().slice(0, 10)) : '-';
  const t = input.dateRange?.to ? (typeof input.dateRange.to === 'string' ? input.dateRange.to : input.dateRange.to.toISOString().slice(0, 10)) : '-';
  doc.text(input.businessName, rightX, top, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Branch: ${input.branchId || '-'}`, rightX, top + 12, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Period: ${f} to ${t}`, rightX, top + 24, { width: rightW, align: 'right', lineBreak: false });
  doc.text(`Generated: ${formatDateTime(input.generatedAt)}`, rightX, top + 36, { width: rightW, align: 'right', lineBreak: false });

  const headerBottom = top + (input.subtitle ? 48 : 44);
  doc.moveTo(x, headerBottom).lineTo(x + pageWidth, headerBottom).lineWidth(0.5).strokeColor('#9ca3af').stroke();
  doc.strokeColor('#000');
  return headerBottom + 12;
}

export function applyHmsPageFooter(doc: any): void {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const x = doc.page.margins.left;
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const footerY = doc.page.height - doc.page.margins.bottom - 14;
    doc.font('Helvetica').fontSize(9).fillColor('#6b7280');
    doc.text('Generated by HMS', x, footerY, { width: pageWidth / 2, align: 'left' });
    doc.text(`Page ${i + 1} of ${range.count}`, x, footerY, { width: pageWidth, align: 'right' });
    doc.fillColor('#000');
  }
}
